name: Ping URL
description: Ping a URL and check if it's reachable

inputs:
  url: # INPUT_URL
    description: The URL to ping
    required: true
  max_retries: # INPUT_MAX_RETRIES
    description: Maximum number of retries
    default: '10'
    required: false
  delay: # INPUT_DELAY
    description: Interval between retries in milliseconds
    default: '5'
    required: false
outputs:
  url-reachable: # OUTPUT_REACHABLE
    description: Whether the URL is reachable
runs:
  using: 'docker'
  image: 'Dockerfile'