name: Cache Node and NPM Dependencies
description: This action allows to cache both  Node and NPM dependencies based en the package-lock.json file

inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    description: The working directory
    default: '.'
    required: false
  target-env:
    description: The target environment
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{inputs.working-dir}}
        key: ${{ runner.os }}-node-${{inputs.target-env}}-${{hashFiles(format('{0}/{1}', inputs.working-dir, 'packages-lock.json'))}}
    - name: Install dependecies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{inputs.working-dir}}