name: 17 - 1 - Custom actions - Composite
run-name: 17 - 1 - Custom actions - Composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: The target environment
        type: choice
        options:
          - dev
          - prod
        default: dev

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory}}
          target-env: ${{ inputs.target-env }}
      - name: Print setup output
        run: |
          echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"
        shell: bash
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build