name: 18 - 3 - Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummy-dir
  e2e-test:
    uses: Bee-Code-Dev/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main